# Generated by Django 5.0.7 on 2024-08-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_reservationtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
