# Generated by Django 5.0.7 on 2024-08-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_menuitem_description_menuitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='inventory',
        ),
    ]
